### ISSUE TITLE
Feature request: categories and tags

### ISSUE THREAD

**Issue by District-Research** [LukasJoswiak/etch#16]
Hi there,

Thanks for such a nice theme, I really like it. 
I do miss being able to assign tags and categories to posts and having them listed upon selecting a given category / tag though. Do you plan to add this feature to your theme?

I'd appreciate your feedback. 
Cheers!

**Comment by LukasJoswiak** [comment]
Hi, thanks for the request -- I added an initial implementation in #18. Being able to organize posts seems like a good idea! I am less of a fan of adding all the tags of a post to each post itself, as to me this often just pollutes the content. This means the taxonomy feature is somewhat hidden currently, as in a user wouldn't know about it by default. However, posts (or other pages) can still include a link to `/tags/`, `/tags/<some-tag>`, `/categories/`, or any other taxonomy name as a means to surface this feature. Let me know if you have any feedback.
