### ISSUE TITLE
Feature request: Last modified date

### ISSUE THREAD

**Issue by jcrd** [LukasJoswiak/etch#17]
This is a great theme for technical writing, which I think benefits from including `lastmod` info.

Thanks!

**Comment by LukasJoswiak** [comment]
Hi, thanks for the request! Do you have a specific implementation in mind? One way to add this would be to simply replace the current date with `lastmod` if `lastmod` > `publish date`, and add the work "Updated" to the beginning. This would hide the publish date though.

**Comment by jcrd** [comment]
That'd be sufficient for me, and maintain the theme's minimalism.

**Comment by Zbergen-cli** [comment]
@LukasJoswiak,  Hi! Thank you so much for the theme!

I would not like to hide the publication date, what and how should I change for this?

**Comment by LukasJoswiak** [comment]
> I would not like to hide the publication date, what and how should I change for this?

You can update this line https://github.com/LukasJoswiak/etch/blob/dd7394ae947782e9d5c0c2abd19d86aebf182fc9/layouts/_default/single.html#L10

to something like

```
Published <time>{{ .Date.Format "January 2, 2006" }}</time> | Updated <time>{{ .Lastmod.Format "January 2, 2006" }}</time>
```
