### ISSUE TITLE
Code blocks too wide

### ISSUE THREAD

**Issue by emiham** [LukasJoswiak/etch#20]
The background of code blocks sticks out quite a bit from the rest of the text. To my eyes this is quite jarring, but I saw you have code blocks on your own blog and don't seem to mind, so maybe it's just me! I thought I'd give you the feedback anyway, but feel free to close this right away if you don't think it's a problem. Love the theme in any case!

**Comment by LukasJoswiak** [comment]
Hi, the extra wide code blocks are done on purpose -- the idea was to give some visual differentiation to code blocks 🙂. Images also have this property. If you want to make the code blocks and images the same width as the rest of the text, it shouldn't be too difficult. You can delete the `width` and `margin-left` properties in the [`main#content pre`](https://github.com/LukasJoswiak/etch/blob/b2941c2fcf93031c5ca8d1bf4e9c781d321c21f7/assets/css/min770px.css#L47) selector to fix the code blocks, and delete the [`main#content figure`](https://github.com/LukasJoswiak/etch/blob/b2941c2fcf93031c5ca8d1bf4e9c781d321c21f7/assets/css/min770px.css#L39) and [`main#content figure img`](https://github.com/LukasJoswiak/etch/blob/b2941c2fcf93031c5ca8d1bf4e9c781d321c21f7/assets/css/min770px.css#L43) selectors to fix the images (all of this should be done in `min770px.css`, as on smaller width screens code blocks and images are already the same width as the text).

This theme is essentially what I thought looked good and wanted to use, packaged up as a Hugo theme. But I definitely don't have the best taste or expect the theme to appeal to everyone, so making changes is encouraged and recommended to customize the theme to your tastes. I'll close the issue now, but feel free to leave any questions or comments you may have.

**Comment by emiham** [comment]
> But I definitely don't have the best taste or expect the theme to appeal to everyone, so making changes is encouraged and recommended to customize the theme to your tastes.

You probably have better taste than me, my seem to be tuned for consistency more than aesthetics. 

Thanks for the instructions on how to change the width, I'll make a fork and tweak everything to my liking.

**Comment by pgrohe** [comment]
Apologies for the 'referenced issue' spam above. Added a link to my personal Etch fork's commit msg, didn't intend for it to spam this issue thread.
