### ISSUE TITLE
Front page blog description not visible

### ISSUE THREAD

**Issue by District-Research** [LukasJoswiak/etch#22]
Hi there! 

Thanks for the great theme once again. I am having an issue with the front page blog description not visible above posts. Please refer to the red frame on the screenshot below. 

May I ask you how could I enable this blog description? 

Thanks!

![11](https://user-images.githubusercontent.com/29061826/120887852-dd972500-c5fd-11eb-9257-6b73f1304590.png)

**Comment by LukasJoswiak** [comment]
You need to create a new file `content/_index.md`. Here's the file from the example site: https://github.com/LukasJoswiak/etch/blob/master/exampleSite/content/_index.md

**Comment by District-Research** [comment]
Thanks! Seems to be working this way.
