### ISSUE TITLE
A topic customization problem.

### ISSUE THREAD

**Issue by uanhi** [LukasJoswiak/etch#25]
Excuse me, **how to set the post text above the article list.**

Because I want to customize it into Chinese.

**Comment by LukasJoswiak** [comment]
To change the informational text on the home page ("This is some info about me" in the demo), add an `_index.md` file in your `content` folder (see the example site https://github.com/LukasJoswiak/etch/blob/master/exampleSite/content/_index.md).

To change the word "Posts", you will have to edit `posts.html` in the theme itself https://github.com/LukasJoswiak/etch/blob/9decabbbad1173f5ea056092a17a7e20d8ccd482/layouts/partials/posts.html#L1.

**Comment by uanhi** [comment]
> To change the informational text on the home page ("This is some info about me" in the demo), add an `_index.md` file in your `content` folder (see the example site https://github.com/LukasJoswiak/etch/blob/master/exampleSite/content/_index.md).
> 
> To change the word "Posts", you will have to edit `posts.html` in the theme itself
> 
> https://github.com/LukasJoswiak/etch/blob/9decabbbad1173f5ea056092a17a7e20d8ccd482/layouts/partials/posts.html#L1
> 
> .

All works well, thanks for your reply.
