### ISSUE TITLE
Taxonomies not working

### ISSUE THREAD

**Issue by bearums** [LukasJoswiak/etch#28]
Hi, 

Great theme, thanks for all your work! 

On your example site the tags and categories pages work fine, but when I download the repo and run the example site locally, the taxonomies pages just show the post list. Is this a bug? 

Thanks

**Comment by LukasJoswiak** [comment]
Can you provide some more info on how you are running the example site with the theme? Tags and categories work fine for me when I run locally.

> the taxonomies pages just show the post list

Which specific taxonomy are you talking about here, `tags` or `categories`?

**Comment by bearums** [comment]
I have checked with the latest version of hugo (0.92), and eveything works fine. However with the older version (~0.6) that is available on APT for ubuntu, then both tags and categories taxonomies show the posts list.

**Comment by LukasJoswiak** [comment]
Unfortunately I have to draw the line somewhere in terms of support, and supporting older versions of Hugo is not something I want to spend my time on. The correct solution to this issue would be to ask the maintainers of the packages to update the Hugo version.
