### ISSUE TITLE
Adding new features

### ISSUE THREAD

**Issue by doliG** [LukasJoswiak/etch#29]
Hello,

I'm using your theme for one of my blogs. I really like the simplicity of it, but sometimes I wish it to have more features.

Here's the features I'm considering adding:
- Date: Use locale to format date
- Date: User can provide custom date format in blog settings
- Taxonomies: Display tags and categories in a post
- Misc: Display custom title for posts (i.e paintings, recipes, talks...)

Are you open to PR or should I fork your repo ?

Thanks

**Comment by LukasJoswiak** [comment]
Hi, thanks for the ideas.

> Date: Use locale to format date
> Date: User can provide custom date format in blog settings
 
These sound like good ideas, accessibility and i18n does not have a lot of support in this theme currently.

> Taxonomies: Display tags and categories in a post

I discussed this a little in https://github.com/LukasJoswiak/etch/issues/16#issuecomment-816397045. I understand the value of showing all tags/categories automatically for each post. But at the same time, this theme is purposely designed to be simple and if supporting many different tags and categories is your goal it might not be the correct theme. Anyway, I'm open to a PR on this, but no guarantees.

> Misc: Display custom title for posts (i.e paintings, recipes, talks...)

I tend to think adding options for things like this causes a trend towards having options for everything, which causes clutter. In my opinion, if someone wants to make this kind of change they should fork the repo and make the change in their fork.

**Comment by doliG** [comment]
I'll tackle taxonomies later (it's not that important).

Regarding the custom title for the posts, I disagree because _post_ is an english word, and have not its place on a translated website.

We can use [hugo i18n](https://gohugo.io/functions/i18n/) to tackle both date format and custom post page title. We could have one `en-US.yaml` file in the theme and to provide a way for the user can just add its own translation [at the root of its project](https://gohugo.io/content-management/multilingual/#translation-of-strings) (`/i18n`) 🤔 

What do you think ?

**Comment by LukasJoswiak** [comment]
Good point, I wasn’t considering the internationalization aspect of the title. That sounds like a good plan to me, would be great to have i18n support!

**Comment by doliG** [comment]
Hey @LukasJoswiak , I've created for you a PR. Please let me now your thoughts :)
