### ISSUE TITLE
Anyway to set a different url when click on the website's name?

### ISSUE THREAD

**Issue by amifelipek** [LukasJoswiak/etch#36]
I just added support to another language on my website but when I click on the website's name it brings me back to the baseURL, anyway to override this when using a different language?

**Comment by LukasJoswiak** [comment]
Hi, did you figure out a way to do this? It seems useful. Based on https://gohugo.io/content-management/multilingual/#configure-multilingual-multihost, it seems the `baseURL` can be set per language. Without having personally tested it, it seems like a plausible solution.

**Comment by amifelipek** [comment]
Hey, yeah I also found that documentation, but if I understood it correctly I need two domains for that to work, is that right? I wanted a simple way to make it point to `baseURL/pt-br` like it's with menus...

**Comment by LukasJoswiak** [comment]
I just tried this out, it seems to work ok to set `baseURL` to have the same domain but different paths.

```
[languages]
  [languages.en]
    baseURL = "https://example.com"
    title = "Website Name"
    weight = 1
  [languages.fr]
    baseURL = "https://example.com/fr/"
    title = "Website Name in French"
    weight = 2
```

Although there was a problem with the CSS not loading on the French version when running in development mode (`hugo server`). Development mode is broken for the French language site because it runs each language on a separate port, but uses the absolute `/css/styles.min.css` path for all sites. There shouldn't be any problems with a site generated through `hugo`, but I'll have to look into fixing this development path issue.

**Comment by amifelipek** [comment]
yeah I had the same problem with the css, I tried using it on production and did not work as well, is there anyway to fix that?

**Comment by LukasJoswiak** [comment]
One way to fix this is to change `$css.RelPermalink` to `$css.Permalink` at https://github.com/LukasJoswiak/etch/blob/1969ea26457aef716efae848c5d08c8a00d75a69/layouts/partials/head.html#L28. I don't think this is the "correct" fix for this problem, but it should work fine as a quick way to get things working.

**Comment by amifelipek** [comment]
How can I ship this change to the theme in my website?

**Comment by LukasJoswiak** [comment]
From the directory containing your site files, edit the file at `themes/etch/layouts/partials/head.html` to make the change above, then rebuild your site with `hugo`.

**Comment by amifelipek** [comment]
Sure but then I'm editing your repo because it's added as a git submodule

**Comment by LukasJoswiak** [comment]
You are only editing your copy of this repo.

**Comment by amifelipek** [comment]
Yes, I was asking if there's some way to make that work, like is there a way to make a copy of your theme and use it instead of the gitsubmodule?

**Comment by LukasJoswiak** [comment]
You can fork this repo and then use the fork as your submodule https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/about-forks.

**Comment by FHEK789** [comment]
Thanks! It's working quite nice now :)
