### ISSUE TITLE
failed to load translations? 

### ISSUE THREAD

**Issue by lexahl** [LukasJoswiak/etch#38]
(base) Mac:sites Lexi$ cd maie
(base) Mac:maie Lexi$ git init
Initialized empty Git repository in /Users/Lexi/Desktop/sites/maie/.git/
(base) Mac:maie Lexi$ git submodule add https://github.com/LukasJoswiak/etch themes/etch
Cloning into '/Users/Lexi/Desktop/sites/maie/themes/etch'...
remote: Enumerating objects: 461, done.
remote: Counting objects: 100% (127/127), done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 461 (delta 97), reused 81 (delta 81), pack-reused 334
Receiving objects: 100% (461/461), 317.00 KiB | 874.00 KiB/s, done.
Resolving deltas: 100% (239/239), done.
(base) Mac:maie Lexi$ echo theme = \"etch\" >> config.toml
(base) Mac:maie Lexi$ hugo server
Error: add site dependencies: load resources: loading translations: "/Users/Lexi/desktop/sites/maie/themes/etch/i18n/en.toml:1:1": failed to load translations: unable to parse translation #0 because invalid plural category date
map[id:posts translation:map[date:map[other:Jan 2, 2006] title:map[other:Posts]]]
(base) Mac:maie Lexi$ hugo version
Hugo Static Site Generator v0.59.1/extended darwin/amd64 BuildDate: unknown

**Comment by LukasJoswiak** [comment]
This is probably because you are using an older version of Hugo. The commands you listed work for me (with the slight caveat that I had to run `echo theme = \"etch\" >> config.toml` to get the quotations to work properly).

```
$ hugo version
hugo v0.96.0+extended darwin/amd64 BuildDate=unknown
```
