### ISSUE TITLE
Body needs to have 100% height to address issue with dark mode

### ISSUE THREAD

**Issue by finestgecko** [LukasJoswiak/etch#4]
I just wanted to give a heads-up about a minor issue with dark mode. On pages with less content, the bottom of the page is white.

I suggest to add `height: 100%` to the `body`.

**Comment by LukasJoswiak** [comment]
Hi, thanks for the heads up! Can you provide details about what environment you saw this issue in (OS, browser, browser version)? I'm unable to reproduce this.

**Comment by joelcieslar** [comment]
I'm using Firefox Nightly 200621 on Android 10 (MIUI Global 11.0.2).

Please refer to [this screenshot](https://uploadpie.com/rk7Epf).

Thanks! :)

**Comment by LukasJoswiak** [comment]
I don't have the right device to reproduce this issue. Please open a PR with the fix and I'll be happy to merge it in. It also looks like you may want to use `min-height: 100%` instead, based on https://stackoverflow.com/a/6654996/986991.

**Comment by finestgecko** [comment]
I'm going to close this issue, since I noticed the problem also sporadically occurs on other websites. I'm inclined to believe that it's not related to Etch.

Feel free to delete. Apologies!
