### ISSUE TITLE
Adding Latex Support/RSS Support

### ISSUE THREAD

**Issue by husainaloos** [LukasJoswiak/etch#7]
It would be great if this theme supports RSS and Latex.

Thanks.

**Comment by LukasJoswiak** [comment]
The theme already has RSS support, linked through a [meta tag on the header of each page](https://github.com/LukasJoswiak/etch/blob/master/layouts/partials/head.html#L8-L10), available at /index.xml. I haven't added a visible RSS button anywhere yet, but if you want one you can add a link to /index.xml in the navigation bar or the footer.

Adding support for LaTeX is out of scope for what I want this theme to be, which is a simple no-frills writing theme, but feel free to create a fork with LaTeX support. It shouldn't be too difficult ([here's one tutorial](https://eankeen.github.io/blog/posts/render-latex-with-katex-in-hugo-blog/)), and there are [already forks which have added support for KaTeX](https://github.com/sivapvarma/etch/commit/b12557e986de538ba6a427e138402ff606633124).
